#!/bin/bash
set -e

echo "Activating conda environment..."
source /srv/conda/etc/profile.d/conda.sh
conda info --envs
conda activate myenv

echo "Conda environment information:"
conda info
conda list

echo "Python version:"
python --version

echo "Importing and checking numpy:"
python -c "import numpy; print('NumPy version:', numpy.__version__)"
echo "Importing and checking pandas:"
python -c "import pandas; print('Pandas version:', pandas.__version__)"
echo "Importing and checking matplotlib:"
python -c "import matplotlib; print('Matplotlib version:', matplotlib.__version__)"

# Print package versions for debugging
#pip list

# Check package versions
#python -c "import numpy; print(numpy.__version__)"
#python -c "import pandas; print(pandas.__version__)"
#python -c "import matplotlib; print(matplotlib.__version__)"
#python -c "import ipywidgets; print(ipywidgets.__version__)"

# Install and enable Voila
pip install voila
jupyter serverextension enable voila --sys-prefix

# Enable the notebook extension for interactive widgets
jupyter nbextension enable --py widgetsnbextension

# If you want to use Voila in JupyterLab
# jupyter labextension install @jupyter-voila/jupyterlab-preview

# Optionally, if you need specific Voila templates
# pip install voila-materialstream
# pip install voila-vuetify

# Clean up (optional, but can help reduce image size)
pip cache purge
rm -rf ~/.cache/yarn
